language: python
sudo: required
python:
- '2.7'
services:
- elasticsearch
- mongodb
env:
- ELASTICSEARCH_HOST=127.0.0.1:9200 MONGO_HOST=127.0.0.1
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.3.1 coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: pypi
  user: tcarel
  password:
    secure: Is9Y4JPbRPYdZbSEpcaG3D3VDqa+wVFvR7YDcgpp5D7SMeShnazIH6hq8GzZTvf7ZBtgC6lHe/cyqrYgBsmMZGoHRTd8g8RlVq8nkmRThcHS8PzCo2yf/3Bd/7Yo3xk+fo/d1TPaulJjhNMT1LNPXOG37lBP2a7bTMcSWD43J7ra/RaTScvVnD0oOOEtxp8eu5Q5kUKAASvxPbE5iJzJZEtdX4Ejw/WSzvIrfWnwbr0xJ2YaN/Cz31syCrZyBC5E9k+fWlEzW2VCKhkqMuy3uLbduqGId5unNlyPqTWN5EgOai7hbuhEMRic2KdWqNMcDmXpF6PODv8HDemMv3kJY8Erpg44wYaTwuzS+lwj3Faf2zLz+H5DQdKoEic1YjHmkbiSv98jucmPHaxmcVTzuwBdl6/AFn9Ga5s3oYG6BChckxP1vM8hM/1ToToZAHyEQ1otr3f034kgJGdIu3kTnIgpATQbv5SG+VAeMERgE6aylns2yTXak3Ssv6GvkTBbahybfWKhHshsCDbcjXET7BNOlXYPD+U1wm9DG2Dcx5DonedpS3UsvTV9Whr63ot4d4YbfhSXHK/CQrJ2NfmBcYgAnbWfpNCJG7YuA3jLud/sM9JlmRJQWEvJb0Bio4IFHNPbySjIyYI1W2NpoGAvqfGoRa2pFKpkkMtiwuDSQto=
  on:
    tags: true
    repo: cogniteev/docido-python-sdk
notifications:
  slack:
    secure: EU8qU8bp5V5GrJzZWxOr8fCjOpUpiMdN4CXjWvEOv2oYrp/BlNrvHaLJK5qFSWvPS+WPgTTisH8ARio0G42H88J8tgoBFyb5DZiUmQvjIg+d/MC/6wp9rxwuxM6RJnevuDcLKqx7JL1CnK7QBr9CW4DSJa47RLYhCFU03KyN6n+YdIcDkl6j+WrjeJwdtOFcEM4jd99DcudEv1QraMhnhI5RMTCyiBInnXpoXvNesEGjlGb/+g7iQZCKtCPv9M+9IS2Kxa8/GTE6CNr9LdzqLRenThzkLmH/jJfZI3xPRP5FkJMlAXRqc8JT9QiZJNROflWOFFZQKJfTDe+07X/z1Pfg6XQFIiyCrVfpTzoEE4+nekP/e9YbPvRJ4zucJjCfsjjB9JffLb8pkeVYoI0yy9IvT1+3WKA47TwaZJK3Z3SbV4NdJwv8Oc6DDXr43ZHA7bBlfEsj9vd9bOGBz4G6O6+b3Q9jugs86G6Wo/Cs1wcPour6XcBKm0s9eJM9t9/amPEaioXpvSMFYJRmiKay0EXj/9ZD86zkuV5HfS9zG5eKIYPkXwQR6BuyMa+xT8JwXFuv+KU6c0Bl7b2roQrHuOGajQAtJlZQ1JJCOvEwbeHuW22uxPPqkL3N9rAsUARubMluhUa2f4Cu32edTdnlk/HuyoPsbdWI23P82Re4rqg=
